services:
  webapp:
    build:
      context: .
    image: node:22-alpine
    ports:
      - "3000:3000"
    volumes:
      - /srv/www/dongdaminhgovap:/app/media
    depends_on:
      - mongo
    env_file:
      - .env.production

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/mongo
    logging:
      driver: none
    env_file:
      - .env.production

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - webapp

  certbot:
    restart: always
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'while :; do certbot renew; sleep 12h; done'"

volumes:
  data:
