services:
  webapp:
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/mongo
    logging:
      driver: none

volumes:
  data:
    name: daminhgovap-data-base
