name: daminhgovap-dev
services:
  webapp:
    image: node:22
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      # unbind these directories from the host
      - /app/node_modules
      - /app/.next
      - /app/.pnpm-store
      # bind source code to the container
      - ./:/app
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=mongo
    command: >
      bash -c "
        corepack enable pnpm &&
        pnpm install &&
        pnpm dev
      "

  mongo:
    env_file:
      - .env.local

volumes:
  data:
    name: daminhgovap-data-dev
