/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    hiddenTags: HiddenTag;
    media: Media;
    pages: Page;
    posts: Post;
    users: User;
    spotifyPodcasts: SpotifyPodcast;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    hiddenTags: HiddenTagsSelect<false> | HiddenTagsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    spotifyPodcasts: SpotifyPodcastsSelect<false> | SpotifyPodcastsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'vi') | ('en' | 'vi')[];
  globals: {
    navBar: NavBar;
    footer: Footer;
    siteSettings: SiteSetting;
  };
  globalsSelect: {
    navBar: NavBarSelect<false> | NavBarSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en' | 'vi';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hiddenTags".
 */
export interface HiddenTag {
  id: string;
  label: string;
  tag: string;
  isPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  publishedAt: string;
  /**
   * Đường dẫn sẽ được sử dụng để truy cập trang này. Luôn bắt đầu bằng "/". Ví dụ: "/gioi-thieu".
   */
  path: string;
  /**
   * Cần mật khẩu để truy cập trang này.
   */
  requireHttpBasicAuth?: boolean | null;
  title: string;
  main?:
    | (
        | {
            items: {
              title: string;
              content: string;
              children?:
                | {
                    title: string;
                    content: string;
                    children?:
                      | {
                          title: string;
                          content: string;
                          id?: string | null;
                        }[]
                      | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'accordionContentBlock';
          }
        | {
            verse: string;
            reference: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bibleVerseBlock';
          }
        | {
            desktopImage: string | Media;
            mobileImage: string | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dynamicImageBlock';
          }
        | {
            image: string | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageBlock';
          }
        | {
            /**
             * Để cân xứng, chọn 5 nếu hiển thị trong layout 1 cột, 4 cho trong layout 2 cột.
             */
            postCount?: ('4' | '5') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'latestPostGridBlock';
          }
        | {
            address: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mapBlock';
          }
        | {
            title: string;
            hidePostTitles: boolean;
            hiddenTags: (string | HiddenTag)[];
            limit?: number | null;
            viewMoreButton: {
              enableViewMoreButton: boolean;
            };
            displayType: 'grid' | 'list';
            id?: string | null;
            blockName?: string | null;
            blockType: 'postGroupBlock';
          }
        | {
            tabs: {
              title: string;
              content: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabbedContentBlock';
          }
        | {
            title: string;
            viewMoreButton: {
              enableViewMoreButton: boolean;
              relativeUrl?: (string | null) | Page;
            };
            tabs?:
              | {
                  title: string;
                  hiddenTags: (string | HiddenTag)[];
                  limit: number;
                  viewMoreButton: {
                    enableViewMoreButton: boolean;
                    relativeUrl?: (string | null) | Page;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabbedPostGroupBlock';
          }
        | {
            content: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            title: string;
            items: {
              title: string;
              description?: string | null;
              thumbnail: string | Media;
              link?: (string | null) | Page;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'timelineBlock';
          }
        | {
            videos: {
              title: string;
              type: 'youtube' | 'facebook';
              url: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoGridBlock';
          }
        | {
            size: number;
            id?: string | null;
            blockName?: string | null;
            blockType: 'spaceBlock';
          }
        | {
            content: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quoteBlock';
          }
        | {
            /**
             * Số lượng podcast hiển thị trên một trang.
             */
            pageSize?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'spotifyPodcastList';
          }
      )[]
    | null;
  banners?: (string | Media)[] | null;
  /**
   * Tùy chỉnh hình trang trí ở mục Nav Bar
   */
  showBannersDecorativeGraphic?: boolean | null;
  beforeMain?:
    | (
        | {
            items: {
              title: string;
              content: string;
              children?:
                | {
                    title: string;
                    content: string;
                    children?:
                      | {
                          title: string;
                          content: string;
                          id?: string | null;
                        }[]
                      | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'accordionContentBlock';
          }
        | {
            verse: string;
            reference: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bibleVerseBlock';
          }
        | {
            desktopImage: string | Media;
            mobileImage: string | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dynamicImageBlock';
          }
        | {
            image: string | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageBlock';
          }
        | {
            /**
             * Để cân xứng, chọn 5 nếu hiển thị trong layout 1 cột, 4 cho trong layout 2 cột.
             */
            postCount?: ('4' | '5') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'latestPostGridBlock';
          }
        | {
            address: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mapBlock';
          }
        | {
            title: string;
            hidePostTitles: boolean;
            hiddenTags: (string | HiddenTag)[];
            limit?: number | null;
            viewMoreButton: {
              enableViewMoreButton: boolean;
            };
            displayType: 'grid' | 'list';
            id?: string | null;
            blockName?: string | null;
            blockType: 'postGroupBlock';
          }
        | {
            tabs: {
              title: string;
              content: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabbedContentBlock';
          }
        | {
            title: string;
            viewMoreButton: {
              enableViewMoreButton: boolean;
              relativeUrl?: (string | null) | Page;
            };
            tabs?:
              | {
                  title: string;
                  hiddenTags: (string | HiddenTag)[];
                  limit: number;
                  viewMoreButton: {
                    enableViewMoreButton: boolean;
                    relativeUrl?: (string | null) | Page;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabbedPostGroupBlock';
          }
        | {
            content: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            title: string;
            items: {
              title: string;
              description?: string | null;
              thumbnail: string | Media;
              link?: (string | null) | Page;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'timelineBlock';
          }
        | {
            videos: {
              title: string;
              type: 'youtube' | 'facebook';
              url: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoGridBlock';
          }
        | {
            size: number;
            id?: string | null;
            blockName?: string | null;
            blockType: 'spaceBlock';
          }
        | {
            content: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quoteBlock';
          }
        | {
            /**
             * Số lượng podcast hiển thị trên một trang.
             */
            pageSize?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'spotifyPodcastList';
          }
      )[]
    | null;
  aside?:
    | (
        | {
            desktopImage: string | Media;
            mobileImage: string | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dynamicImageBlock';
          }
        | {
            image: string | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageBlock';
          }
        | {
            images: (string | Media)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageSlideshowBlock';
          }
        | {
            title: string;
            hidePostTitles: boolean;
            hiddenTags: (string | HiddenTag)[];
            limit?: number | null;
            viewMoreButton: {
              enableViewMoreButton: boolean;
            };
            displayType: 'grid' | 'list';
            id?: string | null;
            blockName?: string | null;
            blockType: 'postGroupBlock';
          }
        | {
            tabs: {
              title: string;
              content: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'tabbedContentBlock';
          }
        | {
            content: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            size: number;
            id?: string | null;
            blockName?: string | null;
            blockType: 'spaceBlock';
          }
        | {
            content: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quoteBlock';
          }
        | {
            title: string;
            links: {
              title: string;
              url: string;
              /**
               * Hình ảnh hiển thị để bấm vào mở liên kết. Hình ảnh sẽ được hiển thị trong khung tỷ lệ 4:1.
               */
              image: string | Media;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'linksBlock';
          }
      )[]
    | null;
  seo?: {
    /**
     * Dùng chung với tiêu đề của mục Nội Dung
     */
    title?: string | null;
    /**
     * Mô tả ngắn về trang
     */
    description?: string | null;
    keywords?: string[] | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  hideTitle?: boolean | null;
  hiddenTags: (string | HiddenTag)[];
  thumbnail: string | Media;
  videos?:
    | {
        title: string;
        type: 'youtube' | 'facebook';
        /**
         * Ví dụ với YouTube, URL là https://www.youtube.com/watch?v=GnX7TN3uo5g thì Video ID là GnX7TN3uo5g. Với Facebook, URL là https://www.facebook.com/watch/?v=123456789 thì Video ID là 123456789.
         */
        videoId: string;
        id?: string | null;
      }[]
    | null;
  contentMode?: ('markdown' | 'template' | 'blocks') | null;
  /**
   * Chọn 1 mẫu giao diện phù hợp để nhập nội dung theo cấu trúc.
   */
  template?:
    | (
        | GospelReflectionSplitBlock
        | GospelReflectionCardBlock
        | SaintBiographyBlock
        | VerticalVideoPrayerBlock
        | NewsArticleFeaturedBlock
        | EventGalleryReportBlock
        | CatechismQASeriesBlock
        | KidsBibleStoryBlock
        | ParableLifeLessonBlock
        | BilingualQuoteCardBlock
        | DominicanSpiritualityBlock
      )[]
    | null;
  /**
   * Tự do ghép các khối nội dung theo nhu cầu.
   */
  contentBlocks?:
    | (
        | AccordionContentBlock
        | BibleVerseBlock
        | DynamicImageBlock
        | ImageBlock
        | ImageSlideShowBlock
        | LatestPostGridBlock
        | LinksBlock
        | MapBlock
        | PostGroupBlock
        | QuoteBlock
        | SpaceBlock
        | SpotifyPodcastList
        | TabbedContentBlock
        | TabbedPostGroupBlock
        | TextBlock
        | TimelineBlock
        | VideoGridBlock
      )[]
    | null;
  body?: string | null;
  /**
   * Chỉ điền 2-3 câu
   */
  shortBody?: string | null;
  seo?: {
    /**
     * Dùng chung với tiêu đề của mục Nội Dung
     */
    title?: string | null;
    /**
     * Mô tả ngắn về bài viết
     */
    description?: string | null;
    keywords?: string[] | null;
  };
  /**
   * Can only use letters (a-z, A-Z), numbers (0-9), and dashes (-, _)
   */
  slug: string;
  publishedAt: string;
  /**
   * Cần mật khẩu để truy cập bài viết này.
   */
  requireHttpBasicAuth?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GospelReflectionSplitBlock".
 */
export interface GospelReflectionSplitBlock {
  liturgyDate: string;
  liturgyWeek: string;
  keyVerse?: string | null;
  reflection: string;
  prayer?: string | null;
  gospel: {
    passage: string;
    reading: string;
    translationCredit?: string | null;
  };
  author?: string | null;
  productionUnit?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gospelReflectionSplit';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GospelReflectionCardBlock".
 */
export interface GospelReflectionCardBlock {
  liturgyMeta: string;
  image?: (string | null) | Media;
  /**
   * Link bài podcast audio chia sẻ suy niệm trên Spotify.
   */
  spotifyUrl: string;
  gospel?: {
    reference?: string | null;
    content?: string | null;
  };
  body: string;
  author?: string | null;
  audioReader?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gospelReflectionCard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SaintBiographyBlock".
 */
export interface SaintBiographyBlock {
  saintName: string;
  saintTitle: string;
  feastDay: string;
  portrait: string | Media;
  mainContent: {
    timeline: {
      periodOrYear: string;
      description: string;
      id?: string | null;
    }[];
    virtues: {
      title: string;
      body: string;
      id?: string | null;
    }[];
    prayer?: string | null;
  };
  references?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'saintBiography';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VerticalVideoPrayerBlock".
 */
export interface VerticalVideoPrayerBlock {
  video: {
    type: 'youtube' | 'facebook';
    videoId: string;
  };
  intentionPrayer: string;
  scriptureAnchor?: {
    verse?: string | null;
    reference?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'verticalVideoPrayer';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsArticleFeaturedBlock".
 */
export interface NewsArticleFeaturedBlock {
  featuredImage: string | Media;
  imageCaption?: string | null;
  imageAlignment: 'left' | 'right' | 'center';
  content: string;
  sourceName?: string | null;
  sourceUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsArticleFeatured';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventGalleryReportBlock".
 */
export interface EventGalleryReportBlock {
  eventTitle: string;
  eventSubtitle?: string | null;
  sections: {
    narrative?: string | null;
    photos?:
      | {
          image: string | Media;
          caption?: string | null;
          id?: string | null;
        }[]
      | null;
    columns: '2' | '3' | '4';
    id?: string | null;
  }[];
  credits?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'eventGalleryReport';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CatechismQASeriesBlock".
 */
export interface CatechismQASeriesBlock {
  title: string;
  introduction: string;
  items: {
    icon?: string | null;
    title: string;
    body: string;
    id?: string | null;
  }[];
  credits?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'catechismQASeries';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "KidsBibleStoryBlock".
 */
export interface KidsBibleStoryBlock {
  title: string;
  subtitle: string;
  summaryCard?: {
    intro?: string | null;
    takeaways?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  content: string;
  memoryQuote?: string | null;
  credits?: {
    presenter?: string | null;
    productionUnit?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'kidsBibleStory';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ParableLifeLessonBlock".
 */
export interface ParableLifeLessonBlock {
  contents: {
    type: 'body' | 'scripture' | 'callout';
    content?: string | null;
    verse?: string | null;
    reference?: string | null;
    id?: string | null;
  }[];
  translator?: string | null;
  source?: {
    name?: string | null;
    url?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'parableLifeLesson';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BilingualQuoteCardBlock".
 */
export interface BilingualQuoteCardBlock {
  author: string;
  source?: string | null;
  original: {
    language: string;
    quote: string;
    caption?: string | null;
  };
  translation: {
    language: string;
    quote: string;
    caption?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'bilingualQuoteCard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DominicanSpiritualityBlock".
 */
export interface DominicanSpiritualityBlock {
  reflectionTitle: string;
  theme?: string | null;
  lead: string;
  points: {
    symbol?: string | null;
    title: string;
    content: string;
    highlightQuote?: string | null;
    id?: string | null;
  }[];
  closingPrayer?: string | null;
  author: string;
  authorAffiliation?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'dominicanSpirituality';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionContentBlock".
 */
export interface AccordionContentBlock {
  items: {
    title: string;
    content: string;
    children?:
      | {
          title: string;
          content: string;
          children?:
            | {
                title: string;
                content: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordionContentBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BibleVerseBlock".
 */
export interface BibleVerseBlock {
  verse: string;
  reference: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'bibleVerseBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DynamicImageBlock".
 */
export interface DynamicImageBlock {
  desktopImage: string | Media;
  mobileImage: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'dynamicImageBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock".
 */
export interface ImageBlock {
  image: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageSlideShowBlock".
 */
export interface ImageSlideShowBlock {
  images: (string | Media)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageSlideshowBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LatestPostGridBlock".
 */
export interface LatestPostGridBlock {
  /**
   * Để cân xứng, chọn 5 nếu hiển thị trong layout 1 cột, 4 cho trong layout 2 cột.
   */
  postCount?: ('4' | '5') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'latestPostGridBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinksBlock".
 */
export interface LinksBlock {
  title: string;
  links: {
    title: string;
    url: string;
    /**
     * Hình ảnh hiển thị để bấm vào mở liên kết. Hình ảnh sẽ được hiển thị trong khung tỷ lệ 4:1.
     */
    image: string | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'linksBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MapBlock".
 */
export interface MapBlock {
  address: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mapBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostGroupBlock".
 */
export interface PostGroupBlock {
  title: string;
  hidePostTitles: boolean;
  hiddenTags: (string | HiddenTag)[];
  limit?: number | null;
  viewMoreButton: {
    enableViewMoreButton: boolean;
  };
  displayType: 'grid' | 'list';
  id?: string | null;
  blockName?: string | null;
  blockType: 'postGroupBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock".
 */
export interface QuoteBlock {
  content: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'quoteBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpaceBlock".
 */
export interface SpaceBlock {
  size: number;
  id?: string | null;
  blockName?: string | null;
  blockType: 'spaceBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpotifyPodcastList".
 */
export interface SpotifyPodcastList {
  /**
   * Số lượng podcast hiển thị trên một trang.
   */
  pageSize?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'spotifyPodcastList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabbedContentBlock".
 */
export interface TabbedContentBlock {
  tabs: {
    title: string;
    content: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'tabbedContentBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabbedPostGroupBlock".
 */
export interface TabbedPostGroupBlock {
  title: string;
  viewMoreButton: {
    enableViewMoreButton: boolean;
    relativeUrl?: (string | null) | Page;
  };
  tabs?:
    | {
        title: string;
        hiddenTags: (string | HiddenTag)[];
        limit: number;
        viewMoreButton: {
          enableViewMoreButton: boolean;
          relativeUrl?: (string | null) | Page;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tabbedPostGroupBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock".
 */
export interface TextBlock {
  content: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'textBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock".
 */
export interface TimelineBlock {
  title: string;
  items: {
    title: string;
    description?: string | null;
    thumbnail: string | Media;
    link?: (string | null) | Page;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'timelineBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoGridBlock".
 */
export interface VideoGridBlock {
  videos: {
    title: string;
    type: 'youtube' | 'facebook';
    url: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoGridBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'admin' | 'manager' | 'editor' | 'author';
  firstName?: string | null;
  lastName?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "spotifyPodcasts".
 */
export interface SpotifyPodcast {
  id: string;
  /**
   * Tên để tìm kiếm và hiển thị trong admin, không ảnh hưởng đến URL của podcast.
   */
  label: string;
  /**
   * Ví dụ với Spotify, URL là https://open.spotify.com/episode/1234ABCD thì Audio ID là 1234ABCD.
   */
  spotifyId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'hiddenTags';
        value: string | HiddenTag;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'spotifyPodcasts';
        value: string | SpotifyPodcast;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hiddenTags_select".
 */
export interface HiddenTagsSelect<T extends boolean = true> {
  label?: T;
  tag?: T;
  isPublic?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  publishedAt?: T;
  path?: T;
  requireHttpBasicAuth?: T;
  title?: T;
  main?:
    | T
    | {
        accordionContentBlock?: T | AccordionContentBlockSelect<T>;
        bibleVerseBlock?: T | BibleVerseBlockSelect<T>;
        dynamicImageBlock?: T | DynamicImageBlockSelect<T>;
        imageBlock?: T | ImageBlockSelect<T>;
        latestPostGridBlock?: T | LatestPostGridBlockSelect<T>;
        mapBlock?: T | MapBlockSelect<T>;
        postGroupBlock?: T | PostGroupBlockSelect<T>;
        tabbedContentBlock?: T | TabbedContentBlockSelect<T>;
        tabbedPostGroupBlock?: T | TabbedPostGroupBlockSelect<T>;
        textBlock?: T | TextBlockSelect<T>;
        timelineBlock?: T | TimelineBlockSelect<T>;
        videoGridBlock?: T | VideoGridBlockSelect<T>;
        spaceBlock?: T | SpaceBlockSelect<T>;
        quoteBlock?: T | QuoteBlockSelect<T>;
        spotifyPodcastList?: T | SpotifyPodcastListSelect<T>;
      };
  banners?: T;
  showBannersDecorativeGraphic?: T;
  beforeMain?:
    | T
    | {
        accordionContentBlock?: T | AccordionContentBlockSelect<T>;
        bibleVerseBlock?: T | BibleVerseBlockSelect<T>;
        dynamicImageBlock?: T | DynamicImageBlockSelect<T>;
        imageBlock?: T | ImageBlockSelect<T>;
        latestPostGridBlock?: T | LatestPostGridBlockSelect<T>;
        mapBlock?: T | MapBlockSelect<T>;
        postGroupBlock?: T | PostGroupBlockSelect<T>;
        tabbedContentBlock?: T | TabbedContentBlockSelect<T>;
        tabbedPostGroupBlock?: T | TabbedPostGroupBlockSelect<T>;
        textBlock?: T | TextBlockSelect<T>;
        timelineBlock?: T | TimelineBlockSelect<T>;
        videoGridBlock?: T | VideoGridBlockSelect<T>;
        spaceBlock?: T | SpaceBlockSelect<T>;
        quoteBlock?: T | QuoteBlockSelect<T>;
        spotifyPodcastList?: T | SpotifyPodcastListSelect<T>;
      };
  aside?:
    | T
    | {
        dynamicImageBlock?: T | DynamicImageBlockSelect<T>;
        imageBlock?: T | ImageBlockSelect<T>;
        imageSlideshowBlock?: T | ImageSlideShowBlockSelect<T>;
        postGroupBlock?: T | PostGroupBlockSelect<T>;
        tabbedContentBlock?: T | TabbedContentBlockSelect<T>;
        textBlock?: T | TextBlockSelect<T>;
        spaceBlock?: T | SpaceBlockSelect<T>;
        quoteBlock?: T | QuoteBlockSelect<T>;
        linksBlock?: T | LinksBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionContentBlock_select".
 */
export interface AccordionContentBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        title?: T;
        content?: T;
        children?:
          | T
          | {
              title?: T;
              content?: T;
              children?:
                | T
                | {
                    title?: T;
                    content?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BibleVerseBlock_select".
 */
export interface BibleVerseBlockSelect<T extends boolean = true> {
  verse?: T;
  reference?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DynamicImageBlock_select".
 */
export interface DynamicImageBlockSelect<T extends boolean = true> {
  desktopImage?: T;
  mobileImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock_select".
 */
export interface ImageBlockSelect<T extends boolean = true> {
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LatestPostGridBlock_select".
 */
export interface LatestPostGridBlockSelect<T extends boolean = true> {
  postCount?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MapBlock_select".
 */
export interface MapBlockSelect<T extends boolean = true> {
  address?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostGroupBlock_select".
 */
export interface PostGroupBlockSelect<T extends boolean = true> {
  title?: T;
  hidePostTitles?: T;
  hiddenTags?: T;
  limit?: T;
  viewMoreButton?:
    | T
    | {
        enableViewMoreButton?: T;
      };
  displayType?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabbedContentBlock_select".
 */
export interface TabbedContentBlockSelect<T extends boolean = true> {
  tabs?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabbedPostGroupBlock_select".
 */
export interface TabbedPostGroupBlockSelect<T extends boolean = true> {
  title?: T;
  viewMoreButton?:
    | T
    | {
        enableViewMoreButton?: T;
        relativeUrl?: T;
      };
  tabs?:
    | T
    | {
        title?: T;
        hiddenTags?: T;
        limit?: T;
        viewMoreButton?:
          | T
          | {
              enableViewMoreButton?: T;
              relativeUrl?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock_select".
 */
export interface TextBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock_select".
 */
export interface TimelineBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        thumbnail?: T;
        link?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoGridBlock_select".
 */
export interface VideoGridBlockSelect<T extends boolean = true> {
  videos?:
    | T
    | {
        title?: T;
        type?: T;
        url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpaceBlock_select".
 */
export interface SpaceBlockSelect<T extends boolean = true> {
  size?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock_select".
 */
export interface QuoteBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpotifyPodcastList_select".
 */
export interface SpotifyPodcastListSelect<T extends boolean = true> {
  pageSize?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageSlideShowBlock_select".
 */
export interface ImageSlideShowBlockSelect<T extends boolean = true> {
  images?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinksBlock_select".
 */
export interface LinksBlockSelect<T extends boolean = true> {
  title?: T;
  links?:
    | T
    | {
        title?: T;
        url?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  hideTitle?: T;
  hiddenTags?: T;
  thumbnail?: T;
  videos?:
    | T
    | {
        title?: T;
        type?: T;
        videoId?: T;
        id?: T;
      };
  contentMode?: T;
  template?:
    | T
    | {
        gospelReflectionSplit?: T | GospelReflectionSplitBlockSelect<T>;
        gospelReflectionCard?: T | GospelReflectionCardBlockSelect<T>;
        saintBiography?: T | SaintBiographyBlockSelect<T>;
        verticalVideoPrayer?: T | VerticalVideoPrayerBlockSelect<T>;
        newsArticleFeatured?: T | NewsArticleFeaturedBlockSelect<T>;
        eventGalleryReport?: T | EventGalleryReportBlockSelect<T>;
        catechismQASeries?: T | CatechismQASeriesBlockSelect<T>;
        kidsBibleStory?: T | KidsBibleStoryBlockSelect<T>;
        parableLifeLesson?: T | ParableLifeLessonBlockSelect<T>;
        bilingualQuoteCard?: T | BilingualQuoteCardBlockSelect<T>;
        dominicanSpirituality?: T | DominicanSpiritualityBlockSelect<T>;
      };
  contentBlocks?:
    | T
    | {
        accordionContentBlock?: T | AccordionContentBlockSelect<T>;
        bibleVerseBlock?: T | BibleVerseBlockSelect<T>;
        dynamicImageBlock?: T | DynamicImageBlockSelect<T>;
        imageBlock?: T | ImageBlockSelect<T>;
        imageSlideshowBlock?: T | ImageSlideShowBlockSelect<T>;
        latestPostGridBlock?: T | LatestPostGridBlockSelect<T>;
        linksBlock?: T | LinksBlockSelect<T>;
        mapBlock?: T | MapBlockSelect<T>;
        postGroupBlock?: T | PostGroupBlockSelect<T>;
        quoteBlock?: T | QuoteBlockSelect<T>;
        spaceBlock?: T | SpaceBlockSelect<T>;
        spotifyPodcastList?: T | SpotifyPodcastListSelect<T>;
        tabbedContentBlock?: T | TabbedContentBlockSelect<T>;
        tabbedPostGroupBlock?: T | TabbedPostGroupBlockSelect<T>;
        textBlock?: T | TextBlockSelect<T>;
        timelineBlock?: T | TimelineBlockSelect<T>;
        videoGridBlock?: T | VideoGridBlockSelect<T>;
      };
  body?: T;
  shortBody?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
      };
  slug?: T;
  publishedAt?: T;
  requireHttpBasicAuth?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GospelReflectionSplitBlock_select".
 */
export interface GospelReflectionSplitBlockSelect<T extends boolean = true> {
  liturgyDate?: T;
  liturgyWeek?: T;
  keyVerse?: T;
  reflection?: T;
  prayer?: T;
  gospel?:
    | T
    | {
        passage?: T;
        reading?: T;
        translationCredit?: T;
      };
  author?: T;
  productionUnit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GospelReflectionCardBlock_select".
 */
export interface GospelReflectionCardBlockSelect<T extends boolean = true> {
  liturgyMeta?: T;
  image?: T;
  spotifyUrl?: T;
  gospel?:
    | T
    | {
        reference?: T;
        content?: T;
      };
  body?: T;
  author?: T;
  audioReader?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SaintBiographyBlock_select".
 */
export interface SaintBiographyBlockSelect<T extends boolean = true> {
  saintName?: T;
  saintTitle?: T;
  feastDay?: T;
  portrait?: T;
  mainContent?:
    | T
    | {
        timeline?:
          | T
          | {
              periodOrYear?: T;
              description?: T;
              id?: T;
            };
        virtues?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
        prayer?: T;
      };
  references?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VerticalVideoPrayerBlock_select".
 */
export interface VerticalVideoPrayerBlockSelect<T extends boolean = true> {
  video?:
    | T
    | {
        type?: T;
        videoId?: T;
      };
  intentionPrayer?: T;
  scriptureAnchor?:
    | T
    | {
        verse?: T;
        reference?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsArticleFeaturedBlock_select".
 */
export interface NewsArticleFeaturedBlockSelect<T extends boolean = true> {
  featuredImage?: T;
  imageCaption?: T;
  imageAlignment?: T;
  content?: T;
  sourceName?: T;
  sourceUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventGalleryReportBlock_select".
 */
export interface EventGalleryReportBlockSelect<T extends boolean = true> {
  eventTitle?: T;
  eventSubtitle?: T;
  sections?:
    | T
    | {
        narrative?: T;
        photos?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
            };
        columns?: T;
        id?: T;
      };
  credits?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CatechismQASeriesBlock_select".
 */
export interface CatechismQASeriesBlockSelect<T extends boolean = true> {
  title?: T;
  introduction?: T;
  items?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  credits?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "KidsBibleStoryBlock_select".
 */
export interface KidsBibleStoryBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  summaryCard?:
    | T
    | {
        intro?: T;
        takeaways?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  content?: T;
  memoryQuote?: T;
  credits?:
    | T
    | {
        presenter?: T;
        productionUnit?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ParableLifeLessonBlock_select".
 */
export interface ParableLifeLessonBlockSelect<T extends boolean = true> {
  contents?:
    | T
    | {
        type?: T;
        content?: T;
        verse?: T;
        reference?: T;
        id?: T;
      };
  translator?: T;
  source?:
    | T
    | {
        name?: T;
        url?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BilingualQuoteCardBlock_select".
 */
export interface BilingualQuoteCardBlockSelect<T extends boolean = true> {
  author?: T;
  source?: T;
  original?:
    | T
    | {
        language?: T;
        quote?: T;
        caption?: T;
      };
  translation?:
    | T
    | {
        language?: T;
        quote?: T;
        caption?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DominicanSpiritualityBlock_select".
 */
export interface DominicanSpiritualityBlockSelect<T extends boolean = true> {
  reflectionTitle?: T;
  theme?: T;
  lead?: T;
  points?:
    | T
    | {
        symbol?: T;
        title?: T;
        content?: T;
        highlightQuote?: T;
        id?: T;
      };
  closingPrayer?: T;
  author?: T;
  authorAffiliation?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  firstName?: T;
  lastName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "spotifyPodcasts_select".
 */
export interface SpotifyPodcastsSelect<T extends boolean = true> {
  label?: T;
  spotifyId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navBar".
 */
export interface NavBar {
  id: string;
  /**
   * Hình trang trí bên dưới thanh điều hướng
   */
  bottomDecorativeGraphic: {
    enable?: boolean | null;
    imageDesktop: string | Media;
    imageMobile: string | Media;
  };
  menu: {
    /**
     * Nhãn hiển thị của mục menu (tùy chọn nếu đã chọn biểu tượng).
     */
    label?: string | null;
    /**
     * Biểu tượng hiển thị phía trước nhãn menu (tùy chọn nếu đã nhập nhãn).
     */
    icon?:
      | (
          | 'home'
          | 'team-gear'
          | 'parchment-quill'
          | 'family-heart'
          | 'hands-heart'
          | 'location-pin'
          | 'burning-candle'
          | 'saint-dominic'
          | 'translation-book'
          | 'palette-brush'
          | 'video-play'
          | 'person-laptop-idea'
          | 'microphone-soundwave'
          | 'music-notes'
          | 'documents-stack'
          | 'globe'
          | 'praying-hands'
          | 'wheat-stalks'
          | 'st-peters-basilica'
          | 'hand-sprinkling-salt'
          | 'radiant-star'
          | 'open-bible-cross'
          | 'person-broadcast'
          | 'human-brain'
          | 'laptop-book'
          | 'dominican-shield'
          | 'user-growth'
          | 'dominican-dog-torch'
          | 'checklist'
          | 'book-lightbulb'
          | 'book-reading'
          | 'heart-jhs-rosary'
          | 'cross-book'
          | 'divider-line'
        )
      | null;
    linkType: 'none' | 'internal' | 'external';
    internalLink?: (string | null) | Page;
    externalLink?: string | null;
    /**
     * Chọn kiểu bố cục hiển thị menu con khi mở rộng trên máy tính.
     */
    layout: 'grid' | 'pillars' | 'tabs-posts';
    subMenu?:
      | {
          label: string;
          /**
           * Biểu tượng tùy chọn cho mục thẻ lưới.
           */
          icon?:
            | (
                | 'home'
                | 'team-gear'
                | 'parchment-quill'
                | 'family-heart'
                | 'hands-heart'
                | 'location-pin'
                | 'burning-candle'
                | 'saint-dominic'
                | 'translation-book'
                | 'palette-brush'
                | 'video-play'
                | 'person-laptop-idea'
                | 'microphone-soundwave'
                | 'music-notes'
                | 'documents-stack'
                | 'globe'
                | 'praying-hands'
                | 'wheat-stalks'
                | 'st-peters-basilica'
                | 'hand-sprinkling-salt'
                | 'radiant-star'
                | 'open-bible-cross'
                | 'person-broadcast'
                | 'human-brain'
                | 'laptop-book'
                | 'dominican-shield'
                | 'user-growth'
                | 'dominican-dog-torch'
                | 'checklist'
                | 'book-lightbulb'
                | 'book-reading'
                | 'heart-jhs-rosary'
                | 'cross-book'
                | 'divider-line'
              )
            | null;
          /**
           * Mô tả ngắn hiển thị dưới tiêu đề trong thẻ lưới.
           */
          description?: string | null;
          linkType: 'none' | 'internal' | 'external';
          internalLink?: (string | null) | Page;
          externalLink?: string | null;
          subMenu?:
            | {
                label: string;
                /**
                 * Biểu tượng tùy chọn.
                 */
                icon?:
                  | (
                      | 'home'
                      | 'team-gear'
                      | 'parchment-quill'
                      | 'family-heart'
                      | 'hands-heart'
                      | 'location-pin'
                      | 'burning-candle'
                      | 'saint-dominic'
                      | 'translation-book'
                      | 'palette-brush'
                      | 'video-play'
                      | 'person-laptop-idea'
                      | 'microphone-soundwave'
                      | 'music-notes'
                      | 'documents-stack'
                      | 'globe'
                      | 'praying-hands'
                      | 'wheat-stalks'
                      | 'st-peters-basilica'
                      | 'hand-sprinkling-salt'
                      | 'radiant-star'
                      | 'open-bible-cross'
                      | 'person-broadcast'
                      | 'human-brain'
                      | 'laptop-book'
                      | 'dominican-shield'
                      | 'user-growth'
                      | 'dominican-dog-torch'
                      | 'checklist'
                      | 'book-lightbulb'
                      | 'book-reading'
                      | 'heart-jhs-rosary'
                      | 'cross-book'
                      | 'divider-line'
                    )
                  | null;
                linkType: 'none' | 'internal' | 'external';
                internalLink?: (string | null) | Page;
                externalLink?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Thêm các cột chủ đề với banner ảnh và các nút liên kết con.
     */
    pillars?:
      | {
          headerBanner: {
            title: string;
            subtitle?: string | null;
            image: string | Media;
            linkType: 'none' | 'internal' | 'external';
            internalLink?: (string | null) | Page;
            externalLink?: string | null;
          };
          links?:
            | {
                label: string;
                /**
                 * Biểu tượng tùy chọn.
                 */
                icon?:
                  | (
                      | 'home'
                      | 'team-gear'
                      | 'parchment-quill'
                      | 'family-heart'
                      | 'hands-heart'
                      | 'location-pin'
                      | 'burning-candle'
                      | 'saint-dominic'
                      | 'translation-book'
                      | 'palette-brush'
                      | 'video-play'
                      | 'person-laptop-idea'
                      | 'microphone-soundwave'
                      | 'music-notes'
                      | 'documents-stack'
                      | 'globe'
                      | 'praying-hands'
                      | 'wheat-stalks'
                      | 'st-peters-basilica'
                      | 'hand-sprinkling-salt'
                      | 'radiant-star'
                      | 'open-bible-cross'
                      | 'person-broadcast'
                      | 'human-brain'
                      | 'laptop-book'
                      | 'dominican-shield'
                      | 'user-growth'
                      | 'dominican-dog-torch'
                      | 'checklist'
                      | 'book-lightbulb'
                      | 'book-reading'
                      | 'heart-jhs-rosary'
                      | 'cross-book'
                      | 'divider-line'
                    )
                  | null;
                linkType: 'none' | 'internal' | 'external';
                internalLink?: (string | null) | Page;
                externalLink?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    bottomBar?: {
      label?: string | null;
      links?:
        | {
            label: string;
            /**
             * Biểu tượng tùy chọn.
             */
            icon?:
              | (
                  | 'home'
                  | 'team-gear'
                  | 'parchment-quill'
                  | 'family-heart'
                  | 'hands-heart'
                  | 'location-pin'
                  | 'burning-candle'
                  | 'saint-dominic'
                  | 'translation-book'
                  | 'palette-brush'
                  | 'video-play'
                  | 'person-laptop-idea'
                  | 'microphone-soundwave'
                  | 'music-notes'
                  | 'documents-stack'
                  | 'globe'
                  | 'praying-hands'
                  | 'wheat-stalks'
                  | 'st-peters-basilica'
                  | 'hand-sprinkling-salt'
                  | 'radiant-star'
                  | 'open-bible-cross'
                  | 'person-broadcast'
                  | 'human-brain'
                  | 'laptop-book'
                  | 'dominican-shield'
                  | 'user-growth'
                  | 'dominican-dog-torch'
                  | 'checklist'
                  | 'book-lightbulb'
                  | 'book-reading'
                  | 'heart-jhs-rosary'
                  | 'cross-book'
                  | 'divider-line'
                )
              | null;
            linkType: 'none' | 'internal' | 'external';
            internalLink?: (string | null) | Page;
            externalLink?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Thêm các mục danh mục bên trái và gắn Thẻ để tự động lấy các bài viết mới nhất.
     */
    categories?:
      | {
          label: string;
          /**
           * Biểu tượng tùy chọn cho danh mục.
           */
          icon?:
            | (
                | 'home'
                | 'team-gear'
                | 'parchment-quill'
                | 'family-heart'
                | 'hands-heart'
                | 'location-pin'
                | 'burning-candle'
                | 'saint-dominic'
                | 'translation-book'
                | 'palette-brush'
                | 'video-play'
                | 'person-laptop-idea'
                | 'microphone-soundwave'
                | 'music-notes'
                | 'documents-stack'
                | 'globe'
                | 'praying-hands'
                | 'wheat-stalks'
                | 'st-peters-basilica'
                | 'hand-sprinkling-salt'
                | 'radiant-star'
                | 'open-bible-cross'
                | 'person-broadcast'
                | 'human-brain'
                | 'laptop-book'
                | 'dominican-shield'
                | 'user-growth'
                | 'dominican-dog-torch'
                | 'checklist'
                | 'book-lightbulb'
                | 'book-reading'
                | 'heart-jhs-rosary'
                | 'cross-book'
                | 'divider-line'
              )
            | null;
          linkType: 'none' | 'internal' | 'external';
          internalLink?: (string | null) | Page;
          externalLink?: string | null;
          /**
           * Chọn các thẻ bài viết để hiển thị lưới bài viết tương ứng.
           */
          tags: (string | HiddenTag)[];
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  topFooterDecorativeGraphic?: (string | null) | Media;
  contact: {
    name: string;
    address: string;
    phone: string;
    email: string;
    marketingEmail?: string | null;
  };
  externalLinks?:
    | {
        name: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: string;
  logo?: (string | null) | Media;
  siteName?: string | null;
  seo?: {
    /**
     * Dùng chung với tên của website trong tab Nội Dung
     */
    title?: string | null;
    /**
     * Mô tả ngắn về website
     */
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navBar_select".
 */
export interface NavBarSelect<T extends boolean = true> {
  bottomDecorativeGraphic?:
    | T
    | {
        enable?: T;
        imageDesktop?: T;
        imageMobile?: T;
      };
  menu?:
    | T
    | {
        label?: T;
        icon?: T;
        linkType?: T;
        internalLink?: T;
        externalLink?: T;
        layout?: T;
        subMenu?:
          | T
          | {
              label?: T;
              icon?: T;
              description?: T;
              linkType?: T;
              internalLink?: T;
              externalLink?: T;
              subMenu?:
                | T
                | {
                    label?: T;
                    icon?: T;
                    linkType?: T;
                    internalLink?: T;
                    externalLink?: T;
                    id?: T;
                  };
              id?: T;
            };
        pillars?:
          | T
          | {
              headerBanner?:
                | T
                | {
                    title?: T;
                    subtitle?: T;
                    image?: T;
                    linkType?: T;
                    internalLink?: T;
                    externalLink?: T;
                  };
              links?:
                | T
                | {
                    label?: T;
                    icon?: T;
                    linkType?: T;
                    internalLink?: T;
                    externalLink?: T;
                    id?: T;
                  };
              id?: T;
            };
        bottomBar?:
          | T
          | {
              label?: T;
              links?:
                | T
                | {
                    label?: T;
                    icon?: T;
                    linkType?: T;
                    internalLink?: T;
                    externalLink?: T;
                    id?: T;
                  };
            };
        categories?:
          | T
          | {
              label?: T;
              icon?: T;
              linkType?: T;
              internalLink?: T;
              externalLink?: T;
              tags?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  topFooterDecorativeGraphic?: T;
  contact?:
    | T
    | {
        name?: T;
        address?: T;
        phone?: T;
        email?: T;
        marketingEmail?: T;
      };
  externalLinks?:
    | T
    | {
        name?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  logo?: T;
  siteName?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}