/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    hiddenTags: HiddenTag;
    media: Media;
    pages: Page;
    posts: Post;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    hiddenTags: HiddenTagsSelect<false> | HiddenTagsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    navBar: NavBar;
    footer: Footer;
    siteSettings: SiteSetting;
  };
  globalsSelect: {
    navBar: NavBarSelect<false> | NavBarSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en' | 'vi';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hiddenTags".
 */
export interface HiddenTag {
  id: string;
  label: string;
  tag: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    'thumbnail-square'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    'thumbnail-square-mobile'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  publishedAt: string;
  /**
   * Đường dẫn sẽ được sử dụng để truy cập trang này. Luôn bắt đầu bằng "/". Ví dụ: "/gioi-thieu".
   */
  path: string;
  title: string;
  main?:
    | (
        | AccordionContentBlock
        | BibleVerseBlock
        | DynamicImageBlock
        | ImageBlock
        | LatestPostGridBlock
        | MapBlock
        | PostGroupBlock
        | TabbedContentBlock
        | TabbedPostGroupBlock
        | TextBlock
        | TimelineBlock
        | VideoGridBlock
        | SpaceBlock
        | QuoteBlock
      )[]
    | null;
  banners?: (string | Media)[] | null;
  /**
   * Tùy chỉnh hình trang trí ở mục Nav Bar
   */
  showBannersDecorativeGraphic?: boolean | null;
  beforeMain?:
    | (
        | AccordionContentBlock
        | BibleVerseBlock
        | DynamicImageBlock
        | ImageBlock
        | LatestPostGridBlock
        | MapBlock
        | PostGroupBlock
        | TabbedContentBlock
        | TabbedPostGroupBlock
        | TextBlock
        | TimelineBlock
        | VideoGridBlock
        | SpaceBlock
        | QuoteBlock
      )[]
    | null;
  aside?:
    | (
        | DynamicImageBlock
        | ImageBlock
        | ImageSlideShowBlock
        | PostGroupBlock
        | TabbedContentBlock
        | TextBlock
        | SpaceBlock
        | QuoteBlock
        | LinksBlock
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionContentBlock".
 */
export interface AccordionContentBlock {
  items: {
    title: string;
    content: string;
    children?:
      | {
          title: string;
          content: string;
          children?:
            | {
                title: string;
                content: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordionContentBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BibleVerseBlock".
 */
export interface BibleVerseBlock {
  verse: string;
  reference: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'bibleVerseBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DynamicImageBlock".
 */
export interface DynamicImageBlock {
  desktopImage: string | Media;
  mobileImage: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'dynamicImageBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock".
 */
export interface ImageBlock {
  image: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LatestPostGridBlock".
 */
export interface LatestPostGridBlock {
  /**
   * Để cân xứng, chọn 5 nếu hiển thị trong layout 1 cột, 4 cho trong layout 2 cột.
   */
  postCount?: ('4' | '5') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'latestPostGridBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MapBlock".
 */
export interface MapBlock {
  address: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mapBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostGroupBlock".
 */
export interface PostGroupBlock {
  title: string;
  hidePostTitles: boolean;
  hiddenTags: (string | HiddenTag)[];
  limit?: number | null;
  viewMoreButton: {
    enableViewMoreButton: boolean;
  };
  displayType: 'grid' | 'list';
  id?: string | null;
  blockName?: string | null;
  blockType: 'postGroupBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabbedContentBlock".
 */
export interface TabbedContentBlock {
  tabs: {
    title: string;
    content: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'tabbedContentBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabbedPostGroupBlock".
 */
export interface TabbedPostGroupBlock {
  title: string;
  viewMoreButton: {
    enableViewMoreButton: boolean;
    relativeUrl?: (string | null) | Page;
  };
  tabs?:
    | {
        title: string;
        hiddenTags: (string | HiddenTag)[];
        limit: number;
        viewMoreButton: {
          enableViewMoreButton: boolean;
          relativeUrl?: (string | null) | Page;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tabbedPostGroupBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock".
 */
export interface TextBlock {
  content: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'textBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock".
 */
export interface TimelineBlock {
  title: string;
  items: {
    title: string;
    description?: string | null;
    thumbnail: string | Media;
    link?: (string | null) | Page;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'timelineBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoGridBlock".
 */
export interface VideoGridBlock {
  videos: {
    title: string;
    type: 'youtube' | 'facebook';
    url: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoGridBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpaceBlock".
 */
export interface SpaceBlock {
  size: number;
  id?: string | null;
  blockName?: string | null;
  blockType: 'spaceBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock".
 */
export interface QuoteBlock {
  content: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'quoteBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageSlideShowBlock".
 */
export interface ImageSlideShowBlock {
  images: (string | Media)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageSlideshowBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinksBlock".
 */
export interface LinksBlock {
  title: string;
  links: {
    title: string;
    url: string;
    /**
     * Hình ảnh hiển thị để bấm vào mở liên kết. Hình ảnh sẽ được hiển thị trong khung tỷ lệ 4:1.
     */
    image: string | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'linksBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  hideTitle?: boolean | null;
  /**
   * Can only use letters (a-z, A-Z), numbers (0-9), and dashes (-, _)
   */
  slug: string;
  publishedAt: string;
  hiddenTags: (string | HiddenTag)[];
  thumbnail: string | Media;
  videos?:
    | {
        title: string;
        type: 'youtube' | 'facebook';
        /**
         * Ví dụ với YouTube, URL là https://www.youtube.com/watch?v=GnX7TN3uo5g thì Video ID là GnX7TN3uo5g. Với Facebook, URL là https://www.facebook.com/watch/?v=123456789 thì Video ID là 123456789.
         */
        videoId: string;
        id?: string | null;
      }[]
    | null;
  body: string;
  /**
   * Chỉ điền 2-3 câu
   */
  shortBody?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'admin' | 'editor';
  firstName?: string | null;
  lastName?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'hiddenTags';
        value: string | HiddenTag;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hiddenTags_select".
 */
export interface HiddenTagsSelect<T extends boolean = true> {
  label?: T;
  tag?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        'thumbnail-square'?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        'thumbnail-square-mobile'?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  publishedAt?: T;
  path?: T;
  title?: T;
  main?:
    | T
    | {
        accordionContentBlock?: T | AccordionContentBlockSelect<T>;
        bibleVerseBlock?: T | BibleVerseBlockSelect<T>;
        dynamicImageBlock?: T | DynamicImageBlockSelect<T>;
        imageBlock?: T | ImageBlockSelect<T>;
        latestPostGridBlock?: T | LatestPostGridBlockSelect<T>;
        mapBlock?: T | MapBlockSelect<T>;
        postGroupBlock?: T | PostGroupBlockSelect<T>;
        tabbedContentBlock?: T | TabbedContentBlockSelect<T>;
        tabbedPostGroupBlock?: T | TabbedPostGroupBlockSelect<T>;
        textBlock?: T | TextBlockSelect<T>;
        timelineBlock?: T | TimelineBlockSelect<T>;
        videoGridBlock?: T | VideoGridBlockSelect<T>;
        spaceBlock?: T | SpaceBlockSelect<T>;
        quoteBlock?: T | QuoteBlockSelect<T>;
      };
  banners?: T;
  showBannersDecorativeGraphic?: T;
  beforeMain?:
    | T
    | {
        accordionContentBlock?: T | AccordionContentBlockSelect<T>;
        bibleVerseBlock?: T | BibleVerseBlockSelect<T>;
        dynamicImageBlock?: T | DynamicImageBlockSelect<T>;
        imageBlock?: T | ImageBlockSelect<T>;
        latestPostGridBlock?: T | LatestPostGridBlockSelect<T>;
        mapBlock?: T | MapBlockSelect<T>;
        postGroupBlock?: T | PostGroupBlockSelect<T>;
        tabbedContentBlock?: T | TabbedContentBlockSelect<T>;
        tabbedPostGroupBlock?: T | TabbedPostGroupBlockSelect<T>;
        textBlock?: T | TextBlockSelect<T>;
        timelineBlock?: T | TimelineBlockSelect<T>;
        videoGridBlock?: T | VideoGridBlockSelect<T>;
        spaceBlock?: T | SpaceBlockSelect<T>;
        quoteBlock?: T | QuoteBlockSelect<T>;
      };
  aside?:
    | T
    | {
        dynamicImageBlock?: T | DynamicImageBlockSelect<T>;
        imageBlock?: T | ImageBlockSelect<T>;
        imageSlideshowBlock?: T | ImageSlideShowBlockSelect<T>;
        postGroupBlock?: T | PostGroupBlockSelect<T>;
        tabbedContentBlock?: T | TabbedContentBlockSelect<T>;
        textBlock?: T | TextBlockSelect<T>;
        spaceBlock?: T | SpaceBlockSelect<T>;
        quoteBlock?: T | QuoteBlockSelect<T>;
        linksBlock?: T | LinksBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionContentBlock_select".
 */
export interface AccordionContentBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        title?: T;
        content?: T;
        children?:
          | T
          | {
              title?: T;
              content?: T;
              children?:
                | T
                | {
                    title?: T;
                    content?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BibleVerseBlock_select".
 */
export interface BibleVerseBlockSelect<T extends boolean = true> {
  verse?: T;
  reference?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DynamicImageBlock_select".
 */
export interface DynamicImageBlockSelect<T extends boolean = true> {
  desktopImage?: T;
  mobileImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock_select".
 */
export interface ImageBlockSelect<T extends boolean = true> {
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LatestPostGridBlock_select".
 */
export interface LatestPostGridBlockSelect<T extends boolean = true> {
  postCount?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MapBlock_select".
 */
export interface MapBlockSelect<T extends boolean = true> {
  address?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostGroupBlock_select".
 */
export interface PostGroupBlockSelect<T extends boolean = true> {
  title?: T;
  hidePostTitles?: T;
  hiddenTags?: T;
  limit?: T;
  viewMoreButton?:
    | T
    | {
        enableViewMoreButton?: T;
      };
  displayType?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabbedContentBlock_select".
 */
export interface TabbedContentBlockSelect<T extends boolean = true> {
  tabs?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabbedPostGroupBlock_select".
 */
export interface TabbedPostGroupBlockSelect<T extends boolean = true> {
  title?: T;
  viewMoreButton?:
    | T
    | {
        enableViewMoreButton?: T;
        relativeUrl?: T;
      };
  tabs?:
    | T
    | {
        title?: T;
        hiddenTags?: T;
        limit?: T;
        viewMoreButton?:
          | T
          | {
              enableViewMoreButton?: T;
              relativeUrl?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock_select".
 */
export interface TextBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock_select".
 */
export interface TimelineBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        thumbnail?: T;
        link?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoGridBlock_select".
 */
export interface VideoGridBlockSelect<T extends boolean = true> {
  videos?:
    | T
    | {
        title?: T;
        type?: T;
        url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpaceBlock_select".
 */
export interface SpaceBlockSelect<T extends boolean = true> {
  size?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock_select".
 */
export interface QuoteBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageSlideShowBlock_select".
 */
export interface ImageSlideShowBlockSelect<T extends boolean = true> {
  images?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinksBlock_select".
 */
export interface LinksBlockSelect<T extends boolean = true> {
  title?: T;
  links?:
    | T
    | {
        title?: T;
        url?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  hideTitle?: T;
  slug?: T;
  publishedAt?: T;
  hiddenTags?: T;
  thumbnail?: T;
  videos?:
    | T
    | {
        title?: T;
        type?: T;
        videoId?: T;
        id?: T;
      };
  body?: T;
  shortBody?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  firstName?: T;
  lastName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navBar".
 */
export interface NavBar {
  id: string;
  /**
   * Hình trang trí bên dưới thanh điều hướng
   */
  bottomDecorativeGraphic: {
    enable?: boolean | null;
    imageDesktop: string | Media;
    imageMobile: string | Media;
  };
  menu: {
    label: string;
    linkType: 'internal' | 'external';
    internalLink?: (string | null) | Page;
    externalLink?: string | null;
    subMenu?:
      | {
          label: string;
          linkType: 'internal' | 'external';
          internalLink?: (string | null) | Page;
          externalLink?: string | null;
          subMenu?:
            | {
                label: string;
                linkType: 'internal' | 'external';
                internalLink?: (string | null) | Page;
                externalLink?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  topFooterDecorativeGraphic?: (string | null) | Media;
  contact: {
    name: string;
    address: string;
    phone: string;
    email: string;
    marketingEmail?: string | null;
  };
  externalLinks?:
    | {
        name: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: string;
  logo?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navBar_select".
 */
export interface NavBarSelect<T extends boolean = true> {
  bottomDecorativeGraphic?:
    | T
    | {
        enable?: T;
        imageDesktop?: T;
        imageMobile?: T;
      };
  menu?:
    | T
    | {
        label?: T;
        linkType?: T;
        internalLink?: T;
        externalLink?: T;
        subMenu?:
          | T
          | {
              label?: T;
              linkType?: T;
              internalLink?: T;
              externalLink?: T;
              subMenu?:
                | T
                | {
                    label?: T;
                    linkType?: T;
                    internalLink?: T;
                    externalLink?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  topFooterDecorativeGraphic?: T;
  contact?:
    | T
    | {
        name?: T;
        address?: T;
        phone?: T;
        email?: T;
        marketingEmail?: T;
      };
  externalLinks?:
    | T
    | {
        name?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}