# run npx decap-server
local_backend: true

backend:
  name: git-gateway
  branch: netlify # Branch to update
  squash_merges: true

# only works with remote backend
publish_mode: editorial_workflow

locale: "vi"

media_library:
  name: cloudinary
  config:
    cloud_name: dxtb6rv7y
    api_key: 897111389275384

media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Trang"
    files:
      - name: "congregation-introduction"
        label: "Giới thiệu hội dòng"
        file: "content/pages/congregation/introduction.md"
        fields:
          - name: "about-us-banner"
            label: "Banner giới thiệu hội dòng"
            widget: image
            required: false
            allow_multiple: false
          - name: "about-us-body"
            label: "Đôi nét về hội dòng"
            widget: markdown
          - name: "about-us-general"
            label: "Đôi nét chính"
            widget: "markdown"
          - name: "about-us-training"
            label: "Chương trình đào tạo"
            widget: "markdown"
          - name: "duties"
            label: "Chúng tôi đã làm gì"
            widget: "markdown"
          - name: "introduction-videos"
            label: "Video giới thiệu"
            widget: "list"
            field:
              { name: "youtube-link", label: "Link youtube", widget: "string" }
          - name: "mission-banner"
            label: "Banner sứ mệnh của hội dòng"
            widget: image
            required: false
            allow_multiple: false
          - name: "body2"
            label: "Đôi nét về sứ mệnh của hội dòng"
            widget: markdown
          - name: "home-for-orphans"
            label: "Mái ấm cho trẻ mồ côi"
            widget: "markdown"
          - name: "care-for-the-disabled"
            label: "Chăm sóc người khuyết tật"
            widget: "markdown"
          - name: "reach-out-to-the-poor"
            label: "Đến với anh em nghèo"
            widget: "markdown"
          - name: "mission-videos"
            label: "Video hoạt động sứ mệnh"
            widget: "list"
            allow_add: true
            field:
              { name: "youtube-link", label: "Link youtube", widget: "string" }
          - name: "where-banner"
            label: "Banner nơi chúng tôi hiện diện"
            widget: image
            required: false
            allow_multiple: false
          - name: "locations"
            label: "Các địa điểm"
            widget: "list"
            allow_add: true
            fields:
              - { name: "name", label: "Tên địa điểm", widget: "string" }
              - {
                  name: "description",
                  label: "Thông tin về địa điểm",
                  widget: "markdown",
                }
      - name: "contact"
        label: "Liên hệ"
        file: "content/pages/contact.md"
        fields:
          - name: "body"
            label: "Thân trang"
            widget: markdown
  - name: "settings"
    label: "Cài đặt"
    editor:
      preview: false
    files:
      - name: "site"
        label: "Cài đặt website"
        file: "content/settings/site.md"
        fields:
          - name: "logo"
            label: "Logo"
            widget: "image"
            allow_multiple: false
      - name: "home"
        label: "Trang chủ"
        file: "content/settings/home.md"
        fields:
          - { name: "hidden", label: "Ẩn", widget: "boolean", default: false }
      - name: "congregation"
        label: "Hội dòng"
        file: "content/settings/congregration.md"
        fields:
          - { name: "hidden", label: "Ẩn", widget: "boolean", default: false }
      - name: "spirituality"
        label: "Linh đạo"
        file: "content/settings/spirituality.md"
        fields:
          - { name: "hidden", label: "Ẩn", widget: "boolean", default: false }
      - name: "missions"
        label: "Sứ vụ"
        file: "content/settings/missions.md"
        fields:
          - { name: "hidden", label: "Ẩn", widget: "boolean", default: false }
      - name: "prayer"
        label: "Cầu nguyện"
        file: "content/settings/prayer.md"
        fields:
          - { name: "hidden", label: "Ẩn", widget: "boolean", default: false }
      - name: "vocation"
        label: "Ơn gọi"
        file: "content/settings/invocation.md"
        fields:
          - { name: "hidden", label: "Ẩn", widget: "boolean", default: false }
      - name: "news"
        label: "Bản tin"
        file: "content/settings/news.md"
        fields:
          - { name: "hidden", label: "Ẩn", widget: "boolean", default: false }
      - name: "special-topics"
        label: "Chuyên đề"
        file: "content/settings/special-topics.md"
        fields:
          - { name: "hidden", label: "Ẩn", widget: "boolean", default: false }
      - name: "footer"
        label: "Chân trang"
        file: "content/settings/footer.md"
        fields:
          - {
              name: "name",
              label: "Tên",
              widget: "string",
              default: "HỘI DÒNG NỮ ĐA MINH GÒ VẤP",
            }
          - { name: "address", label: "Địa chỉ", widget: "string" }
          - { name: "email", label: "Email", widget: "string" }
          - { name: "phone", label: "Điện thoại", widget: "string" }
          - { name: "facebook", label: "Facebook", widget: "string" }
          - { name: "youtube", label: "Youtube", widget: "string" }
          - { name: "zalo", label: "Zalo", widget: "string" }
  - name: posts
    label: "Bài viết"
    create: true
    preview_path: posts/{{year}}/{{month}}/{{title}}
    folder: "content/posts"
    fields:
      - { name: title, label: Tiêu đề }
      - { name: date, label: Date, widget: datetime }
      - { name: videoPost, label: "Bài viết video", widget: boolean }
      - { name: body, label: Body, widget: markdown }
# This collection requires `path_preview_date_field` because
